################################# PLATFORM DETECTION ###############################

# Platform detection function
function(detect_platform)
    set(DETECTED_PLATFORM "UNKNOWN" PARENT_SCOPE)
    
    # Check for WSL2 (must be checked before generic Linux detection)
    if(EXISTS "/proc/version")
        file(READ "/proc/version" PROC_VERSION)
        if(PROC_VERSION MATCHES "microsoft|wsl" OR PROC_VERSION MATCHES "WSL")
            set(DETECTED_PLATFORM "WSL2" PARENT_SCOPE)
            message(STATUS "Platform auto-detected: Windows Subsystem for Linux 2 (WSL2)")
            return()
        endif()
    endif()
    
    # Check for Raspberry Pi
    if(EXISTS "/proc/device-tree/model")
        file(READ "/proc/device-tree/model" RPI_MODEL)
        if(RPI_MODEL MATCHES "Raspberry Pi")
            set(DETECTED_PLATFORM "RPI" PARENT_SCOPE)
            message(STATUS "Platform auto-detected: Raspberry Pi")
            return()
        endif()
    endif()
    
    # Check for NVIDIA Jetson
    if(EXISTS "/proc/device-tree/model")
        file(READ "/proc/device-tree/model" JETSON_MODEL)
        if(JETSON_MODEL MATCHES "Jetson")
            set(DETECTED_PLATFORM "NVIDIA" PARENT_SCOPE)
            message(STATUS "Platform auto-detected: NVIDIA Jetson")
            return()
        endif()
    endif()
    
    # Fallback: check for environment variables
    if(DEFINED ENV{JETSON_TARGETS})
        set(DETECTED_PLATFORM "NVIDIA" PARENT_SCOPE)
        message(STATUS "Platform detected via environment: NVIDIA Jetson")
        return()
    endif()
    
    message(STATUS "Platform auto-detection: Could not detect hardware, defaulting to HOST")
    set(DETECTED_PLATFORM "HOST" PARENT_SCOPE)
endfunction()

# Auto-detect or use explicit choice
string(COMPARE EQUAL "${PLATFORM_CHOICE}" "NVIDIA" IS_NVIDIA)
string(COMPARE EQUAL "${PLATFORM_CHOICE}" "AUTO" IS_AUTO)
string(COMPARE EQUAL "${PLATFORM_CHOICE}" "RPI" IS_RPI)
string(COMPARE EQUAL "${PLATFORM_CHOICE}" "HOST" IS_HOST)
string(COMPARE EQUAL "${PLATFORM_CHOICE}" "WSL2" IS_WSL2)

if(IS_AUTO)
    detect_platform()
    if(DETECTED_PLATFORM STREQUAL "NVIDIA")
        set(NVIDIA ON CACHE BOOL "Set to ON when building on NVIDIA" FORCE)
    elseif(DETECTED_PLATFORM STREQUAL "RPI")
        set(RPI ON CACHE BOOL "Set to ON when building on Raspberry Pi" FORCE)
    elseif(DETECTED_PLATFORM STREQUAL "WSL2")
        set(WSL2 ON CACHE BOOL "Set to ON when building on Windows Subsystem for Linux 2" FORCE)
    elseif(DETECTED_PLATFORM STREQUAL "HOST")
        message(STATUS "Platform auto-detected: HOST (no platform-specific flags)")
    else()
        message(FATAL_ERROR "Unknown platform detected: ${DETECTED_PLATFORM}")
    endif()
elseif(IS_NVIDIA)
    set(NVIDIA ON CACHE BOOL "Set to ON when building on NVIDIA" FORCE)
    message(STATUS "Platform explicitly set to: NVIDIA")
elseif(IS_RPI)
    set(RPI ON CACHE BOOL "Set to ON when building on Raspberry Pi" FORCE)
    message(STATUS "Platform explicitly set to: Raspberry Pi")
elseif(IS_WSL2)
    set(WSL2 ON CACHE BOOL "Set to ON when building on Windows Subsystem for Linux 2" FORCE)
    message(STATUS "Platform explicitly set to: Windows Subsystem for Linux 2 (WSL2)")
elseif(IS_HOST)
    message(STATUS "Platform set to: HOST (no platform-specific flags)")
else()
    message(FATAL_ERROR "Invalid PLATFORM_CHOICE: ${PLATFORM_CHOICE}. Use AUTO, NVIDIA, RPI, WSL2, or HOST.")
endif()

