[package]
name = "adacm-installer"
version = "0.1.0"
edition = "2021"

[dependencies]
include_dir = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "2.1"
indicatif = "0.17"
dirs = "5.0"